/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HundRouteImport } from './routes/hund'
import { Route as KatzeRouteImport } from './routes/katze'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as BoxIndexRouteImport } from './routes/box.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HundRoute = HundRouteImport.update({
  id: '/hund',
  path: '/hund',
  getParentRoute: () => rootRouteImport,
} as any)
const KatzeRoute = KatzeRouteImport.update({
  id: '/katze',
  path: '/katze',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxIndexRoute = BoxIndexRouteImport.update({
  id: '/box/',
  path: '/box/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hund': typeof HundRoute
  '/katze': typeof KatzeRoute
  '/shop': typeof ShopRoute
  '/box/': typeof BoxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hund': typeof HundRoute
  '/katze': typeof KatzeRoute
  '/shop': typeof ShopRoute
  '/box': typeof BoxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hund': typeof HundRoute
  '/katze': typeof KatzeRoute
  '/shop': typeof ShopRoute
  '/box/': typeof BoxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hund' | '/katze' | '/shop' | '/box/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hund' | '/katze' | '/shop' | '/box'
  id: '__root__' | '/' | '/hund' | '/katze' | '/shop' | '/box/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HundRoute: typeof HundRoute
  KatzeRoute: typeof KatzeRoute
  ShopRoute: typeof ShopRoute
  BoxIndexRoute: typeof BoxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hund': {
      id: '/hund'
      path: '/hund'
      fullPath: '/hund'
      preLoaderRoute: typeof HundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katze': {
      id: '/katze'
      path: '/katze'
      fullPath: '/katze'
      preLoaderRoute: typeof KatzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/': {
      id: '/box/'
      path: '/box'
      fullPath: '/box/'
      preLoaderRoute: typeof BoxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HundRoute: HundRoute,
  KatzeRoute: KatzeRoute,
  ShopRoute: ShopRoute,
  BoxIndexRoute: BoxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
